/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto3;

import java.awt.Font;
import javax.swing.JOptionPane;



/**
 *
 * @author nestor2502
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setVisible(false);
        this.setTitle("Proyecto 3");
        this.setResizable(false);
        
         TextPrompt placeholder = new TextPrompt("Nombre completo", nombre);
         placeholder.changeAlpha(0.75f);
         placeholder.changeStyle(Font.ITALIC);
         
         TextPrompt placeholder1 = new TextPrompt("Nombre de usuario", usuario);
         placeholder1.changeAlpha(0.75f);
         placeholder1.changeStyle(Font.ITALIC);
         
         TextPrompt placeholder2 = new TextPrompt("Direccion de correo electronico", correo);
         placeholder2.changeAlpha(0.75f);
         placeholder2.changeStyle(Font.ITALIC);
         
         TextPrompt placeholder3 = new TextPrompt("Contraseña", contrasena);
         placeholder3.changeAlpha(0.75f);
         placeholder3.changeStyle(Font.ITALIC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        contrasena = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Comienza tu aventura con una cuenta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 520, 60));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 560, 50));
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 560, 50));
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 560, 50));
        getContentPane().add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 560, 50));

        crear.setBackground(new java.awt.Color(90, 90, 78));
        crear.setForeground(new java.awt.Color(240, 240, 240));
        crear.setText("Crear cuenta");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        getContentPane().add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 190, 60));

        fondo2.setBackground(new java.awt.Color(38, 38, 38));
        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto3/1080x720-00001.jpg"))); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
          int contador=0;
          boolean correcto1 = false;
          int correcto =0;
          String nombre1 = nombre.getText().trim();
          String usuario1 = usuario.getText().trim();
          String correo1 =correo.getText().trim();
          String contraseña1 =contrasena.getText().trim();
          
          
       
        
        //verificacion de email
        String email = correo1;
        if(email.equals("")==false||!email.equals(" ")==false){
         for(int i = 0 ; i<email.length(); i++){

             	  if(email.charAt(i)=='@')

             	  	  correcto ++;
                  if(email.charAt(i)=='.')

             	  	  correcto ++;
             }

             if(correcto != 2){

             	 //System.out.println("Incorrecto");
             	 JOptionPane.showMessageDialog(null, "Correo incorrecto");
             }
             else{
         //verifica que los campos no esténvacios     
            if(nombre1.equals("")||usuario1.equals("")||correo1.equals("")||contraseña1.equals("")){
               JOptionPane.showMessageDialog(null, "No dejes campos vacios");
        }
        else contador++;}}
        else{
            if(nombre1.equals("")||usuario1.equals("")||correo1.equals("")||contraseña1.equals(""))
               JOptionPane.showMessageDialog(null, "No dejes campos vacios");
         }

         
        
        
        
        
            
    }//GEN-LAST:event_crearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contrasena;
    private javax.swing.JTextField correo;
    private javax.swing.JButton crear;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
