/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto3;

import java.awt.Font;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author isayd
 */
public class Wapuesta extends javax.swing.JFrame {

    public Equipos EquipoA;
    public Equipos EquipoB;

    /**
     * Creates new form Wapuesta
     */
    public Wapuesta() {
        Equipos Seoul = new Equipos("Seoul Dynasty", 200, "Seoul.png");
        Equipos Houston = new Equipos("Houston Outlaws", 180, "Houston.png");
        EquipoA = Seoul;
        EquipoB = Houston;
        initComponents();
            
        ImageIcon imagen1 = new ImageIcon(getClass().getResource(EquipoA.getImagen())); 
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(Primero.getWidth(), Primero.getHeight(), Image.SCALE_DEFAULT));
        Primero.setIcon(fondo1);
       
        ImageIcon imagen2 = new ImageIcon(getClass().getResource(EquipoB.getImagen()));
        Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(Segundo.getWidth(),Segundo.getHeight(),Image.SCALE_DEFAULT));
        Segundo.setIcon(fondo2);
        
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/proyecto3/Fondillo.jpg"));
        Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(Fondo.getWidth(),Fondo.getHeight(),Image.SCALE_DEFAULT));
        Fondo.setIcon(fondo3);
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setVisible(false);
        this.setTitle("Proyecto 3");
        this.setResizable(false);

        Torneo.setContentAreaFilled(false);
      /**  
      *  Boton1.setContentAreaFilled(false);
      *  Boton1.setVisible(false);
      *  Boton1.setEnabled(false);
      */  
        Boton1.setContentAreaFilled(false);
         TextPrompt placeholder = new TextPrompt("$0.00", Apuesta1);
         placeholder.changeAlpha(0.75f);
         placeholder.changeStyle(Font.ITALIC);
         
         Boton2.setContentAreaFilled(false);
         TextPrompt placeholder1 = new TextPrompt("$0.00", Apuesta2);
         placeholder.changeAlpha(0.75f);
         placeholder.changeStyle(Font.ITALIC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton1 = new javax.swing.JButton();
        Apuesta1 = new javax.swing.JTextField();
        Boton2 = new javax.swing.JButton();
        Torneo = new javax.swing.JButton();
        Apuesta2 = new javax.swing.JTextField();
        Segundo = new javax.swing.JLabel();
        Primero = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton1.setBackground(new java.awt.Color(255, 255, 255));
        Boton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton1.setText("Apostar");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });
        getContentPane().add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        Apuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apuesta1ActionPerformed(evt);
            }
        });
        getContentPane().add(Apuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 90, 40));

        Boton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Boton2.setText("Apostar");
        getContentPane().add(Boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        Torneo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Torneo.setText("Torneo");
        Torneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TorneoActionPerformed(evt);
            }
        });
        getContentPane().add(Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 180, 50));
        getContentPane().add(Apuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 90, 40));
        getContentPane().add(Segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 210, 210));
        getContentPane().add(Primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, 210));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto3/Fondillo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Apuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apuesta1ActionPerformed

    private void TorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TorneoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TorneoActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wapuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wapuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wapuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wapuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wapuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apuesta1;
    private javax.swing.JTextField Apuesta2;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Primero;
    private javax.swing.JLabel Segundo;
    private javax.swing.JButton Torneo;
    // End of variables declaration//GEN-END:variables
}
